export default {
"login": "itaditya",
"id": 15871340,
"node_id": "MDQ6VXNlcjE1ODcxMzQw",
"avatar_url": "https://avatars.githubusercontent.com/u/15871340?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/itaditya",
"html_url": "https://github.com/itaditya",
"followers_url": "https://api.github.com/users/itaditya/followers",
"following_url": "https://api.github.com/users/itaditya/following{/other_user}",
"gists_url": "https://api.github.com/users/itaditya/gists{/gist_id}",
"starred_url": "https://api.github.com/users/itaditya/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/itaditya/subscriptions",
"organizations_url": "https://api.github.com/users/itaditya/orgs",
"repos_url": "https://api.github.com/users/itaditya/repos",
"events_url": "https://api.github.com/users/itaditya/events{/privacy}",
"received_events_url": "https://api.github.com/users/itaditya/received_events",
"type": "User",
"site_admin": false,
"name": "Aditya Agarwal",
"company": "@razorpay",
"blog": "https://devadi.netlify.app",
"location": "Bangalore, India",
"email": null,
"hireable": true,
"bio": "\r\n    Web Dev @razorpay, GSoC Alum @github\r\n\r\n\r\nDo Everything JS: React, Node, Vue.\r\n",
"twitter_username": "dev__adi",
"public_repos": 375,
"public_gists": 118,
"followers": 642,
"following": 447,
"created_at": "2015-11-16T13:08:12Z",
"updated_at": "2022-06-25T17:08:12Z"
}